---
- hosts: 172.31.33.48
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
       name: apache2
       state: present
    #   when: myresult.stderr !=""   
  - name: copy file into ansible node side
    copy:
        src: staticfile.txt
        dest : /home/ubuntu/mystaticfile.txt

  - name: copy index.j2 file into ansible node
    template:
         src: myindex.j2 
         dest: /var/www/html/index.html      

  - name: download internet files
    get_url:
        url: https://get.jenkins.io/war-stable/2.375.2/jenkins.war
        dest: /home/ubuntu/jenkins.war
        force_basic_auth: yes  