---
- hosts: 172.31.33.48
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
       name: apache2
       state: present
    #   when: myresult.stderr !=""   
  - name: copy file into ansible node side
    copy:
        src: staticfile.txt
        dest : /home/ubuntu/mystaticfile.txt