---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install java on ubuntu
    apt:
       name: "{{webpackonubjava}}"
       state: present
    when: ansible_os_family =="Debian"

  
  # - name: i want to start java on ubuntu ansible node
  #   service: 
  #       name: "{{webpackonubuntu}}" 
  #       state: restarted
  #   when: ansible_os_family=="Debian"    

  - name: i want to install java on redhat ansible node
    yum:
       name: "{{webpackonredjava}}"
       state: present
    when: ansible_os_family=="RedHat"   

  # - name: i want to install webserver on redhat ansible node
  #   yum:
  #      name: "{{webpackonredhat}}"
  #      state: started
  #   when: ansible_os_family=="RedHat"  