---
- hosts: 172.31.33.48
  become: yes
  tasks:
  - name: execute linux command
    command:  hostname -f
    register: myresult 

  - name: i want to display my first task result
    debug: 
        msg: "{{myresult}}"
  - name: i want install git
    apt: 
       name: git
       state: present
    when: myresult.stderr !=""   
  - name: i want install tree
    apt:
       name: tree
       state: present
    when: myresult.stderr ==""     
  - name: i want install wget
    apt: 
        name: wget
        state: present

